#!/bin/bash
#SBATCH -J bzp1_ref1076_sph13aa
#SBATCH -o bzp1_ref1076_sph13aa.log
#SBATCH -e bzp1_ref1076_sph13aa.e%j
#SBATCH -p skx-normal
#SBATCH -N 71
#SBATCH -n 1562
#SBATCH -c 1
#SBATCH -t 4:00:00

module load intel/18.0.2
module load hdf5/1.10.4
module load my_gamess/srs-avx-512

SCR_DIR="$SCRATCH/gamess_scratch_$SLURM_JOB_ID"
[[ ! -d $SCR_DIR ]] && mkdir $SCR_DIR
cp bzp1_ref1076_sph13aa.F40 $SCR_DIR/bzp1_ref1076_sph13aa.F40.0000

rungms.tom.keep_files bzp1_ref1076_sph13aa.inp 00 $SLURM_NTASKS
